package com.example.demo.security;

public enum Permission {
    AUTH_LOGIN,
    VIEW_SWITCH_TOUR_GUIDE,
    ORDERS_READ,
    ORDERS_WRITE,
    ORDERS_DELETE,
    ORDERS_OFFER,
    ORDERS_CONFIRM,
    ORDER_GUESTS_MANAGE,
    ASSIGNMENTS_READ,
    ASSIGNMENTS_ASSIGN,
    ITINERARY_WRITE,
    RECEIPTS_OPS_READ,
    ACCOUNTING_READ,
    ACCOUNTING_CLOSE,
    GUIDE_TOURS_READ,
    GUIDE_ASSIGNMENT_RESPOND,
    GUIDE_WORK_LIFECYCLE,
    GUIDE_RECEIPTS_WRITE,
    GUIDE_SALARY_READ
}
